### ISSUE TITLE
[Suggestion] When gravity disabled, make Birch and Dark Oak Logs accessible

### ISSUE THREAD

**Issue by RisingInIris2017** [XYROC/DeltaHardMode#1]
> Birch and Dark Oak Tree Log blocks will no longer drop their blocks when broke (Meant to counter-balance the following change)
Birch and Dark Oak Wooden Plank blocks aren’t affect by gravity (Makes it so that Woodland Mansions don’t immediately fall apart when spawned)

Quoted from [Delta Hard Mode's Official Page](http://xiroc.ovh/deltahardmode/deltahardmode).
But in the latest DHM Mod version DeltaHardMode-1.12.x-0.5.7, even I disabled Gravity mechanic in config file, Birch and Dark Oak logs cannot be harvested.
I have tried to add Birch and Dark Oak into dropBlocks.json:
```JSON
[
  "minecraft:leaves",
  "minecraft:leaves2",
  "minecraft:tallgrass",
  "minecraft:log",
  "minecraft:log2",
]
```
But it did not work.
If there is a way to get Birch and Dark Oak logs after disabled gravity, please tell me.
If there is not such a method yet, may I suggest to enable players harvest those logs after gravity is disabled in the config?
Look forward to your reply!
Thanks in advance!

**Comment by xyroc** [comment]
Oh, that is actually true. The birch and dark oak logs can never be harvested, regardless of the gravity setting. I think i will remove that entirely in the 1.14/1.15 update which i will do sometime. Also sorry for the late reply, this somehow went completely unnoticed by me. 😄

**Comment by RisingInIris2017** [comment]
Thanks for your reply!
I hope to play your new DeltaHardMode mod soon :)

**Comment by xyroc** [comment]
Added in 0.5.9. Enjoy!
