### ISSUE TITLE
Server crashes when players enter: NoSuchMethodError

### ISSUE THREAD

**Issue by RisingInIris2017** [XYROC/DeltaHardMode#2]
#### Mod version:

DeltaHardMode-1.12.x-0.5.7.jar 

#### Forge version:
14.23.5.2847

#### Installed mods:
Attached in crash-reports.
Before the second crash, I removed Foamfix Mod to make sure this issue is not related to Foamfix.

#### Singleplayer or Multiplayer
Multiplayer, using [Mohist](https://github.com/Mohist-Community/Mohist/) Server.

## Link to full crash log
The first crash(Foamfix installed) https://paste.ubuntu.com/p/YS2585xhc3/
The second one((Foamfix not installed))：https://paste.ubuntu.com/p/Vd8DgTZPK9/

#### How to reproduce:
1. Players log in.
2. “Internal Error” message is shown, at the same time server crashes.

I have reported to the Mohist server: https://github.com/Mohist-Community/Mohist/issues/206#issuecomment-611541686
Due to Mohist's developer is a Chinese, I used Chinese to write that issue.
But he replied in English, maybe it is helpful.

Thanks for your kind help in advance!

**Comment by xyroc** [comment]
Thanks, I fixed that. Version 0.5.8 is on curseforge now.
