### ISSUE TITLE
Server Crash when starting: NoClassDefFoundError

### ISSUE THREAD

**Issue by RisingInIris2017** [XYROC/DeltaHardMode#3]
#### Mod version:

DeltaHardMode-1.12.x-0.5.8.jar 

#### Forge version:
14.23.5.2847

#### Installed mods:
Attached in crash-reports.

#### Singleplayer or Multiplayer
Multiplayer, using [Catserver](https://github.com/Luohuayu/CatServer).

## Link to full crash log
https://paste.ubuntu.com/p/Hnqs7rtC6t/

#### How to reproduce:
Simply start server and it will crash several seconds later.

Thanks for your kind help in advance!

**Comment by xyroc** [comment]
Damn, there is a lot if bad code in delta hard mode... Version 0.5.9 should fix the crash.
